### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by paishin** [thaiat/angular-fbopen#1]
Hello there, 

I can see that @ccoenraets has updated the original fbopen plugin with the feature to logout from facebook in https://github.com/ccoenraets/OpenFB in version 3. 

angular-fbopen is still at version 2, are there plans to update this plugin?

**Comment by thaiat** [comment]
you wanna submit a PR

**Comment by paishin** [comment]
I'm sorry I am very new to github so I am not sure what a PR is

**Comment by thaiat** [comment]
a pull request, that s the way you submit code change
